export const Texts = {
  // Alerts
  noPickedDate: 'Niste izabralio nijedan datum za pretragu po lokacijama.',
  noPickedLocation: 'Niste izabralio nijednu lokaciju za pretragu po lokacijama.',
  noPickedDateForBestAndWorst: 'Niste izabralio nijednu datum za pretragu za najbolji i najgori dan.',
  noPickedLocationForBestAndWorst: 'Niste izabralio nijednu lokaciju za pretragu za najbolji i najgori dan.',

  // Text in components
  comparisonPageTitle: 'RAZLIKA KA UPRAVI',
  differenceAllTime: 'Razlika oduvek',
  differenceForPeriodOfTime: 'Razlika za period',
  differenceByLocation: 'Razlika o lokacijama',
  month: 'Mesec',
  day: 'Dan',
  date: 'Datum',
  search: 'PRETRAZI',
  cancel: 'Odustani',
  importFile: 'Uvezi fajl',
  sendToServer: 'Posalji na server',
  weekInYear: 'Nedelja u godini',
  weekInMonth: 'Nedelja u mesecu',
  duration: 'Trajanje od - do',
  valuesInWeek: 'Vrednost u nedelji',
  bestDateInMount: 'Najbolji datum u mesecu',
  bestDayInMount: 'Najbolji dan u mesecu',
  value: 'Vrednost',
  location: 'Lokacija',
  total: 'Total',
  average: 'Prosek',
  navBarEfficiency: 'Efikasnost',
  navBarAttendance: 'Posecenost',
  navBarDifference: 'razlika ka upravi',
  attendancePageHeader: 'POSECENOST PO LOKACIJAMA',
  searchAttendanceByLocation: 'Pretraga za posecenost po lokacijama',
  attendanceByLocation: 'Posecenost po lokacijama',
  bestAndWorstDayPartHeader: 'NAJBOLJI I NAJGORI DAN',
  dataForAllTime: 'Podaci oduvek',
  dataForChosenMount: 'Podaci u izabranim mesecima',
  userName: 'Korisnicko ime',
  userNamePlaceholder: 'Unesi korisnicko ime',
  userNameRequiredValidationError: 'Polje korisnicko ime je obavezno.',
  userNameMinLengthValidationError: 'Korisnicko ime mora biti duze od 5 karaktera',
  password: 'Lozinka',
  passwordVisibility: 'Vidljivost Lozinke',
  passwordPlaceholder: 'Unesite lozinku',
  passwordRequiredValidationError: 'Polje lozinka je obavezno.',
  passwordMinLengthValidationError: 'Lozinka mora biti duze od 5 karaktera',
  login: 'Prijava',
  mainPageHeader: 'TRANSAKCIJE PO LOKACIJAMA',
  searchDataByLocation: 'Pretraga za podatke po lokacijama',
  searchByLocation: 'Pretraga po lokacijama',
  dataAboutLocation: 'Podaci o lokacijama',
  searchDataByMachine: 'Pretraga za podatke po masinama',
  dataAboutMachine: 'Podaci o masinama',
  dataInChosenMounts: 'Podaci u izabranim mesecima',
};
